### ISSUE TITLE
Prototype navigation

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#92]
## Objective

TBD.

## Background

Handled together with #63.

**Comment by matthiasrohmer** [comment]
What are your plans on the `.ad-o-header-background` element? Would it make sense to move it to a dedicated stage organism/molecule or do you consider it as a part of the header?

**Comment by keevcodes** [comment]
@matthiasrohmer good question; admittedly atomic design was not something I thought of while building the prototype. My initial thought would be that since the .ad-o-header-background would be part of the the overall navigation organism, but will change depending on the current page it should be it's own molecule, however I would like to discuss this further with the team 😄
